name: resourse_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^6.1.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.6
  dio: ^5.1.2
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  talker_flutter: ^3.1.1
  get_it: ^7.6.0
  formz: ^0.6.0
  intl: ^0.18.0
  auto_route: ^7.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/home.svg
    - assets/icons/profile.svg
    - assets/icons/reels.svg
    - assets/images/profile.png

  fonts:
    - family: BrunoAceSC
      fonts:
        - asset: assets/fonts/BrunoAceSC-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: Ysabeau
      fonts:
        - asset: assets/fonts/Ysabeau-VariableFont_wght.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
flutter_intl:
  enabled: true
