name: resourse_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^6.1.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.6
  dio: ^5.1.2
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8
  talker_flutter: ^3.1.1
  get_it: ^7.6.0
  formz: ^0.6.0
  intl: ^0.18.0
  auto_route: ^7.8.0
  font_awesome_flutter: 10.4.0
  table_calendar: ^3.0.9
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^15.1.1
  rxdart: ^0.27.7
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: BrunoAceSC
      fonts:
        - asset: assets/fonts/BrunoAceSC-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: Ysabeau
      fonts:
        - asset: assets/fonts/Ysabeau-VariableFont_wght.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
flutter_intl:
  enabled: true

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icons/ic_resource.png"
  image_path_ios: "assets/icons/ic_resource.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
#  web:
#    generate: true
#    image_path: "assets/images/icon-1024x1024.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "assets/images/icon-1024x1024.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "assets/images/icon-1024x1024.png"